# Generated by Django 3.2.9 on 2021-12-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='like',
        ),
        migrations.RemoveField(
            model_name='question',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='question',
            name='like',
        ),
        migrations.AddField(
            model_name='answer',
            name='dislikes',
            field=models.ManyToManyField(default=None, related_name='a_dislikes', to='home.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='a_likes', to='home.User'),
        ),
        migrations.AddField(
            model_name='question',
            name='dislikes',
            field=models.ManyToManyField(default=None, related_name='q_dislikes', to='home.User'),
        ),
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='q_likes', to='home.User'),
        ),
    ]
