# Generated by Django 3.2.9 on 2021-12-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='a_dislikes', to='home.User'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='a_likes', to='home.User'),
        ),
    ]
